ktdreyer/jenkins-job-wrecker

jenkins_job_wrecker/cli.py, setup.py
And fixes some errors to point to -s not -j which is not defined
=> allow passing in username and password via environment variables

README.rst
Sorry! meant to do this in the previous PR
=> update the Readme

.gitignore, jenkins_job_wrecker/cli.py, jenkins_job_wrecker/job_handlers.py
Added some changes we have used. Also, made it pep8 compliant.
=> Johan brkt improvements

jenkins_job_wrecker/job_handlers.py
Add support for:
* Timestamper plug-in
* ArtifactArchiver's latest-only
* EnvInject properties
=> Support a few more tags

jenkins_job_wrecker/cli.py, jenkins_job_wrecker/job_handlers.py
Add support for HG and fix a couple of issues.
The support for multiple entries in the YAML file as well as the SCM split requires more eyes. Would appreciate review on those patches.
=> Add more tags (2015-10-15)

README.rst
Provides a link to the package on PyPI
=> README.rst: add version badge

jenkins_job_wrecker/job_handlers.py
properties - Throttling, Slack, handling of choice parameter
git - local branch extension
builders - BatchFile, Maven
publishers - GroovyPostbuildRecorder
wrappers - MaskPasswordsBuildWrapper
top level jdk node
=> adding more tags

jenkins_job_wrecker/job_handlers.py
* slack publisher
* workspace-cleanup
* post-tasks
Also:
* added get_bool, as when I ran this against our jenkins jobs, that function was missing.
* Altered a debug statement to print out the extension tag it crashed on, instead of the parent
=> Add support for more tags

setup.py
Fix whitespace/indentations to satisfy pylint
=> setup.py: pylint fixes

setup.py
This allows me to sign, tag, and push new versions by running
python setup.py release -s
=> setup.py: add "release" sub-command

jenkins_job_wrecker/cli.py, jenkins_job_wrecker/job_handlers.py
Resolve issues #10 and #16 by adding logic to capture the raw XML of a section that doesn't otherwise
have handling, instead of throwing a NotImplementedError.
=> Add Logic for Raw XML

.gitignore, jenkins_job_wrecker/cli.py
This will resolve #24, allowing directories to be given in the output
filename. The given directory structure will be created before
attempting to write to the file.
=> Support directories in output filename

jenkins_job_wrecker/cli.py
ascii codec to utf8 codec
utf8 supports more language.
=> ascii2utf8

jenkins_job_wrecker/job_handlers.py
Subversion was not handled so far. this PR offers just that.
=> Add subversion (svn) SCM handler

jenkins_job_wrecker/job_handlers.py
Add basic python axis handling
=> Handle python axis

.gitignore, jenkins_job_wrecker/builders.py, jenkins_job_wrecker/job_handlers.py, setup.py
Allows using the jenkins_job_wrecker.builders entry point to add custom builders
=> Changes to allow flexibly adding builders

jenkins_job_wrecker/modules/triggers.py
Fixes to issues encountered during testing.
=> Fixes addition of reverse build triggers

jenkins_job_wrecker/modules/triggers.py
Fix a bad copy & paste from the scm trigger error message here.
=> triggers: fix error message for reverse trigger

jenkins_job_wrecker/modules/triggers.py
"child" is undefined in this context.
=> triggers: fix ignore-post-commit-hooks setting

jenkins_job_wrecker/modules/handlers.py, jenkins_job_wrecker/modules/sandbox.py, jenkins_job_wrecker/modules/script.py, jenkins_job_wrecker/modules/scriptpath.py, jenkins_job_wrecker/registry.py
Ok I think I managed to implement the release-flow mentioned in #43
=> add flow-definition handling

jenkins_job_wrecker/modules/properties.py
=> Fix issue #51

jenkins_job_wrecker/cli.py, jenkins_job_wrecker/modules/builders.py, jenkins_job_wrecker/modules/handlers.py, jenkins_job_wrecker/modules/properties.py, jenkins_job_wrecker/modules/publishers.py, jenkins_job_wrecker/modules/sandbox.py, jenkins_job_wrecker/modules/scm.py, jenkins_job_wrecker/modules/script.py, jenkins_job_wrecker/modules/scriptpath.py, jenkins_job_wrecker/registry.py, tests/test_cli.py, tests/test_jjb.py
Fix all of the outstanding flake8 issues.
I intend to enable flake8 checks as part of "setup.py test" in a future PR.
=> flake8 fixes

jenkins_job_wrecker/modules/buildwrappers.py
Fix for #59.
I can make this smaller with a regex and dictionary for the type, if desired. Tested with the example from #59 and works great.
Let me know if you want any changes made. More than happy to! Thanks.
=> feat: implement buildtimeoutwrapper

jenkins_job_wrecker/modules/lightweight.py
I have a PR out of JJB, I'm waiting for that to be approved and merged. Once it is, we can merge this in whenever.
We can make the decision whether to wait for them to add it into a release version or merge when it gets added to a beta version...
=> Add pipeline lightweight checkout support

jenkins_job_wrecker/cli.py, jenkins_job_wrecker/modules/buildwrappers.py, jenkins_job_wrecker/modules/handlers.py, jenkins_job_wrecker/modules/properties.py, jenkins_job_wrecker/modules/publishers.py
Also added some stuff for concurrent builds with pipeline jobs, as the way the tags work for that are kinda weird.
=> Added slack and secretbuildwrapper support

jenkins_job_wrecker/modules/buildwrappers.py
Fixes issue: https://github.com/ktdreyer/jenkins-job-wrecker/issues/87
=> Fix UnboundLocalError for variable 'subelement'

.stickler.yml
stickler-ci.com is a service that automatically lints new pull requests and applies fixes to pull requests.
=> add Stickler CI configuration

jenkins_job_wrecker/modules/buildwrappers.py, tests/fixtures/buildwrappers/prebuildcleanup.xml, tests/test_modules_buildwrappers.py
JJB now supports all the missing pieces, so added support for that.
=> Extend support for PreBuildCleanup build wrapper

README.rst
This change is to recognize my personal and my team's current and future submissions to this repository.
=> Update copyright statement to include Liberty Global contributions

jenkins_job_wrecker/modules/builders.py, tests/fixtures/builders/build-name-setter.xml, tests/test_modules_builders.py
I have added support for plugin: buildnameupdater
Also written a test case as well.
=> Added support for Build Name Updater plugin

jenkins_job_wrecker/modules/handlers.py, tests/fixtures/handlers/combination-filter.xml, tests/test_modules_handlers.py
According to JJB: https://docs.openstack.org/infra/jenkins-job-builder/project_matrix.html
Otherwise, it does not work.
=> Combination filter needs to be under execution-strategy

jenkins_job_wrecker/cli.py, tests/fixtures/indentation.xml, tests/fixtures/indentation.yml, tests/test_jjb.py
=> Fixes indentation problem on multiline yaml keys.

jenkins_job_wrecker/modules/properties.py, tests/fixtures/properties/rebuild-settings.xml, tests/test_modules_properties.py
=> Added support for rebuildsettings

jenkins_job_wrecker/helpers.py, jenkins_job_wrecker/modules/triggers.py, tests/fixtures/triggers/gerrit_trigger.xml, tests/fixtures/triggers/gerrit_trigger.yml, tests/test_modules_triggers.py
Have revised the implementation, fixed "exclude-drafts".
=> Implementation of gerrit trigger plugin to JJW

jenkins_job_wrecker/modules/properties.py, tests/fixtures/properties/build-blocker-property-with-blocking-jobs.xml, tests/fixtures/properties/build-blocker-property-without-blocking-jobs.xml, tests/test_modules_properties.py
=> Added buildblockerproperty with tests
