ktdreyer/jenkins-job-wrecker

jenkins_job_wrecker/cli.py, jenkins_job_wrecker/job_handlers.py
To make the yaml more readable when it's using long
shell scripts, they should be rendered as literals.
This works for the majority of shell scripts, although
the yaml dump refuses to render some strings as literals
when they look like they should be fine. This isn't a bug
with wrecker, the data is going to the yaml dumper correctly,
but there's something in the string that the dumper doesn't
like
Also, fixed a small bug in the workspace-cleanup conversion.
The clean-if field should have been a list of dicts, not a dict.
This has been tested with our CI Jenkins instance, converting all
of our jobs to yaml, then back again to xml with notnownikki/jenkins-job-builder master,
which hs cherrypicks of certain plugins that we use that are still up
for review in gerrit.
=> Render `script` and `shell` as literals, fix workspace-cleanup bug

jenkins_job_wrecker/cli.py
This will resolve #18, casued by the list of ignored jobs being checked even
when the ignore argument had not been used.
=> Fix broken "convert all jobs on server" function

setup.py
Fix a couple of whitespace things that bother flake8.
Add NOQA to a particularly long trove classifier line.
=> setup.py: flake8 fixes

setup.py
This saves a manual step when releasing.
=> setup.py: push master branch

jenkins_job_wrecker/job_handlers.py
I recently ran into a Jenkins job that uses this plugin:
`<org.jenkinsci.plugins.ghprb.GhprbTrigger plugin="ghprb@1.33.1">`
which for some reason had an empty `adminlist`:
`<adminlist></adminlist>`
This caused an `AttributeError`:
```
$ jjwrecker -f sample-job.xml -n sample-job
last called handle_triggers
Traceback (most recent call last):
[...]
File "/path/to/jenkins_job_wrecker/job_handlers.py", line 536, in handle_triggers
ghpr['admin-list'] = ghprel.text.strip().split('\n')
AttributeError: 'NoneType' object has no attribute 'strip'
```
This PR should deal with it.
=> fix issue with empty adminlist

jenkins_job_wrecker/cli.py
I noticed that importing (using as a library) causes issues with logging, e.g.
`from jenkins_job_wrecker.cli import root_to_yaml`
I also found this:
http://pieces.openpolitics.com/2012/04/python-logging-best-practices/
This change should fix the logging issues without negatively impacting the command-line use-case of `jjwrecker`:
- Before
```
jjwrecker INFO: looking up job "acceptance_tests_china"
jjwrecker INFO: converting job "acceptance_tests_china" to YAML
```
- After
```
INFO:jjwrecker:looking up job "acceptance_tests_china"
INFO:jjwrecker:converting job "acceptance_tests_china" to YAML
```
=> Remove custom logging formatter

jenkins_job_wrecker/cli.py, jenkins_job_wrecker/modules/builders.py, jenkins_job_wrecker/modules/properties.py, jenkins_job_wrecker/modules/publishers.py, jenkins_job_wrecker/registry.py, setup.py
- Check buildtrigger is not a parameterized trigger
- Mailer: 'send email on every failed build' is inverse bool
- Remove entry_point for batchfile to prevent conflicts
- Amended registry to allow flexibly defining supported project types
- Updated registry to check for duplicate entry points and raise exception if so
- Fixed parameter parsing, added support for text and file parameters
=> Various fixes

jenkins_job_wrecker/modules/properties.py
this function is called without being properly imported.
=> add missing import statement

jenkins_job_wrecker/cli.py, jenkins_job_wrecker/modules/builders.py, tests/fixtures/non-ascii.xml, tests/test_jjb.py
I got `UnicodeDecodeError` when using non-ascii character in shell script.
```
UnicodeDecodeError: 'utf8' codec can't decode byte 0xe3 in position 0: unexpected end of data
```
I added some non-ascii test. This test can can reproduce the error on `v1.0.11` or `v1.1.0`(latest), but not on `v1.0.10`. So is seems `v1.0.11` is the first version to reproduce.
https://github.com/ktdreyer/jenkins-job-wrecker/compare/v1.0.10...v1.0.11
I think this error occurred by following reasons.
- `xml.etree.ElementTree` parses xml text node as type `<unicode>`, when a xml text node contains non-ascii character.
- In Shell builder, shell script text was converted to type `str` by calling `str(shell_element.text)`.   https://github.com/ktdreyer/jenkins-job-wrecker/blob/master/jenkins_job_wrecker/builders.py#L8 …
=> Fix issue with non-ascii character in shell script text

jenkins_job_wrecker/modules/publishers.py
`slacknotifier` uses `re.sub` but it is not imported in the module.
=> Add missing re import for slack publisher

jenkins_job_wrecker/registry.py
registry.py currently assumes 'flow-definition' means 'flow' in jenkins-job-builder, when it actually means 'com.cloudbees.plugins.flow.BuildFlow'. Correcting this to prevent incorrect yaml being created for pipeline projects.
=> Correct tag for flow

MANIFEST.in
I translated the README to rST a while back but forgot to drop this
line from MANIFEST.in.
Setuptools automatically includes any file named "README.rst" so we
don't need to list it explicitly here.
=> MANIFEST.in: drop non-existent README file

jenkins_job_wrecker/modules/publishers.py
Parameterized build triggers are not being filled in properly, currently:
- Parameters are not translated to yaml
- Multiple triggers are ignored and copied as raw xml
This should fix both these issues to translate the xml to jjb yaml correctly.
=> Fix parameterized build triggers

jenkins_job_wrecker/modules/handlers.py
JJB uses 'sequential' instead of run-sequentially.
See https://git.openstack.org/cgit/openstack-infra/jenkins-job-builder/tree/jenkins_jobs/modules/project_matrix.py#n52
```
* **execution-strategy** (optional, built in Jenkins):
* **combination-filter** (`str`): axes selection filter
* **sequential** (`bool`): run builds sequentially (default false)
* **touchstone** (optional):
* **expr** (`str`) -- selection filter for the touchstone build
* **result** (`str`) -- required result of the job: \
stable (default) or unstable
```
=> Fix bug with incorrect name for sequential in execution-strategy

jenkins_job_wrecker/cli.py
default value is 'output' to keep existing behaviour
=> option -o (--ouput-dir) allows to specify output dir

jenkins_job_wrecker/cli.py, jenkins_job_wrecker/modules/handlers.py, jenkins_job_wrecker/modules/properties.py, jenkins_job_wrecker/modules/scm.py, jenkins_job_wrecker/registry.py
I was able to get basic pipeline configs working. This basically:
1. Adds the flow-definition to get_project_types()
2. Adds support for the pipeline-scm info, as it is in a definition block. This PR handles the different yaml syntax for that.
3. Fixes the GitHub PR Builder support for pipelines. The Github PR builder configuration goes into a <triggers> block inside of the <properties> block (as discussed in #69). This PR checks for that in the properties class and makes a Trigger object if it sees that.
4. Makes the hard fail on the <actions> tag optional. This PR adds a command line argument (`-a` or `--ignore-action-tag`) to just completely ignore the actions info if it finds information in it. This is useful if there is any action info that isn't mission critical but the user still …
=> Pipeline script beginning support

jenkins_job_wrecker/cli.py, jenkins_job_wrecker/modules/handlers.py
I noticed some bugs yesterday after running the script across our Jenkins server.
First being that I used the short name of jobs as the key in the `job_names` dictionary, so if two folders were named the same but were located in different parent folders, one would overwrite the other in the dictionary. I realized that short name isn't really needed anyways, so I've converted job_names back to a list that only stores the full names of jobs.
The other being that I forgot about having raw DSL as an option for pipeline scripts, so I have added that as well. I'm curious what you think about this part @ktdreyer, I feel like there should be a better way to do this, but the format of the tags are weird so the way I did it may be the only way. I can post an example of what the XML looks like and …
=> Fix some bugs with Pipeline and Folder stuff

jenkins_job_wrecker/modules/properties.py
Line 71: JJB doesn't have a tag for sandbox (I don't think they included support for the script-security plugin). I decided to just ignore it because I'd rather have everything else converted to YAML instead of nothing because of that one tag. I'd be curious on your opinion of that, @ktdreyer. I'm not sure if this problem has been addressed in the past or not.
=> Add support for envInject property

setup.py
* Make setup.py use `print()`
* Change `python setup.py release` to call the modern tools I use:
* Use `gpg2` to sign
* Use `twine` to upload
* whitespace flake8 fix
=> setup.py: signing, upload, and flake8 fixes

jenkins_job_wrecker/modules/publishers.py
Accidentally left in print statement and had the notifications key/value switched.
That's what I get for merging before I test my code one last time :).
=> Quick fix for slack notifier

jenkins_job_wrecker/cli.py, setup.py
Fixes #90 
Now -o my_output_folder  is working as expected.
=> Pass in the user specified output directory to convert_to_yml function

.travis.yml, setup.py
This change "fixes" Travis CI failures on current HEAD of master:
- https://travis-ci.com/github/ktdreyer/jenkins-job-wrecker/jobs/334483381
PyYAML used by JJB no longer supports Python 3.4. As it's old enough
folks should migrate to a newer version anyway.
=> Fix CI builds: drop support for Python 3.4 and fix pytest invocation

jenkins_job_wrecker/modules/scm.py
"getchildren()" seemed to work.
=> modules/scm.py: Call 'getchildren()', rather than use '._children'

jenkins_job_wrecker/modules/publishers.py, tests/fixtures/publishers/groovy-postbuild-v2.xml, tests/test_modules_publishers.py
Add support for Groovy Postbuild plugin v2.0+
From https://plugins.jenkins.io/groovy-postbuild/:
> From version 2.0, Groovy Postbuild plugin introduces Script Security Plugin.
This change adds support for the markup generated by the plugin in v2.0+.
Also got rid of the useless 'continue' statement which was silently ignoring unknown markup, rather than letting the wrecker convert it into raw XML.
=> Groovy Postbuild plugin v2 support

.gitignore, .travis.yml, setup.py, tox.ini
Run `pytest` within `tox` instead of `setuptools`.
Setuptools' `test` command might be deprecated in the future, and `tox` makes it easier to test multiple Python versions locally.
=> run tests with tox

jenkins_job_wrecker/modules/handlers.py, tests/fixtures/handlers/child-custom-workspace.xml, tests/test_modules_handlers.py
Added support child custom workspace which is a parameter from matrix type jobs. Added a test case.
=> Support for Child custom workspace

README.rst
In my previous commit I used Markdown markup, not ReStructuredText (sic!). I've fixed my mistake, but the canonical RST way of doing line breaks (prefixing lines with `|`) apparently [doesn't work on GitHub READMEs](https://gist.github.com/dupuy/1855764#line-blocks-and-hard-line-breaks), so switched to lists in the end.
=> Fix copyright formatting in README (again)

jenkins_job_wrecker/modules/buildwrappers.py, tests/fixtures/buildwrappers/prebuildcleanup_empty_value.xml, tests/test_modules_buildwrappers.py
Updated buildwrappers.py to prevent empty attributes on xml converting as `- key: null` and added a new test case for validation.
Validated by @aromanek and @vdanaila
=> Fix prebuildcleanup returning empty attributes as null

jenkins_job_wrecker/modules/buildwrappers.py, tests/fixtures/buildwrappers/awsbindings.xml, tests/test_modules_buildwrappers.py
Found a typo in how AWS credentials are appended to the list of bindings in the `secretbuildwrapper` function.  Added a test for it as well.  Thanks for putting this together!  It's saving me a ton of headaches converting my Jenkins jobs to JJB!
=> fix(typo): fix typo in aws credentials secretbuildwrapper
